# Generated by Django 3.0.6 on 2020-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200514_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(choices=[('MOLDOVA', 'Moldova'), ('ROMANIA', 'Romania'), ('GERMANY', 'Germany'), ('RUSSIA', 'Rusia'), ('ITALY', 'Italy'), ('SPAIN', 'Spain'), ('FRANCE', 'France')], default=None, max_length=25),
        ),
    ]
